spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

server:
  servlet:
    context-path: /api/v1
    session:
      cookie:
        max-age: 604800 # 쿠키 만료 시간: 7일 (초 단위)
        path: "/"       # 쿠키 경로
        secure: false    # HTTPS 환경에서만 쿠키 전송
        http-only: true # JavaScript에서 쿠키 접근 금지
        same-site: lax  # SameSite 설정
      timeout: 7d       # 세션 유지 시간: 7일

logging:
  level:
    org.springframework.security: DEBUG
